### PR TITLE
Gingerbread

### PR DESCRIPTION
**Pull request by Whitexp**
fixed wifi ,cleanups ,removed wrongs confis on boardconfig !!

please no disturb again :P

### CODE REVIEW

**Comment by Whitexp** [comment]
wrong*

**Comment by Whitexp** [comment]
@bieltv3  done !

**Comment by Whitexp** [comment]
@bieltv3  done

now merge lol

**Comment by bieltura** [comment]
THanks alot dude, you're the best ever! thanks alot, and if you want to contribute to cm10.1 on my device tree bieltv.3 I'm making a bcm21553-common and cooperve tree for join androidarmv6 repo thanks alot again your're awsome!

**Pull request merged**
