### PR TITLE
FileManager.

### PR DESCRIPTION
**Pull request by YoYoZ**
I added a file manager. Will you show some entusiasm, biel?:)

### CODE REVIEW

**Comment by bieltura** [comment]
Is it cm7 stock file manager?

**Comment by YoYoZ** [comment]
No it's not. I suppose this version can work. Need to test it, although.

**Comment by bieltura** [comment]
Cm7 original file manager work, no need to add an extra one, will add cm7 original in a few hours, Im bussy now, closed but thanks and will add u credits

**Comment by YoYoZ** [comment]
Okay, will search for some more programs\fixes for CM.

**Pull request closed without merging**
